#!/usr/bin/env python3

# Transliteration table for Sanskrit
# The right-side of the romanization scheme (what is produced in latex) complies with
# https://en.wikipedia.org/wiki/International_Alphabet_of_Sanskrit_Transliteration
# The left-side of the romanization scheme (what is expected in notation) is mostly
# borrowed from: http://www.medieval.org/music/world/carnatic/shyama.html

latex_sanskrit = {
# translit_table = {
# Vowels
    'a': 'a',
    'A': r'\={a}',
    'i': 'i',
    'I': r'\={\i}',
    'u': 'u',
    'U': r'\={u}',
    'R': r'\d{r}',
    'e': 'e',        # Although the distinction between 'e' and '\={e}' doesn't really exist in Sanskrit, we retain this for neatness
    'E': r'\={e}',
    'ai': 'ai',
    'o': 'o',        # Although the distinction between 'e' and '\={e}' doesn't really exist in Sanskrit, we retain this for neatness
    'O': r'\={o}',
    'ow': 'ow',
    'au': 'au',
    'M': r'\d{m}',
    'H': r'\d{h}',
    '\'': '\'',
# Consonants
    'k': 'k',
    'kh': 'kh',
    'g': 'g',
    'gh': 'gh',
    'HN': r'\.{n}',
    'c': 'c',
    'ch': 'ch',
    'j': 'j',
    'jh': 'jh',
    'Hn': r'\~{n}',
    'T': r'\d{t}',
    'Th': r'\d{t}h',
    'D': r'\d{d}',
    'Dh': r'\d{d}h',
    'N': r'\d{n}',
    't': 't',
    'th': 'th',
    'd': 'd',
    'dh': 'dh',
    'n': 'n',
    'p': 'p',
    'ph': 'ph',
    'b': 'b',
    'bh': 'bh',
    'm': 'm',
    'y': 'y',
    'r': 'r',
    'l': 'l',
    'L': r'\d{l}',
    'v': 'v',
    'sh': '\\\'{s}',
    'S': r'\.{s}',    # This is strictly the correct version, but 'Sh' is also allowed
    'Sh': r'\.{s}',
    's': 's',
    'h': 'h',
}


latex_sanskrit_capital = {
# Vowels
    'a': 'a',
    'aa': r'\={a}',
    'i': 'i',
    'ee': r'\={\i}',
    'u': 'u',
    'oo': r'\={u}',
    'rR': r'\d{r}',
    'e': r'\={e}',
    'ai': 'ai',
    'o': r'\={o}',
    'ow': 'ow',
    'au': 'au',
    'mM': r'\d{m}',
    'hH': r'\d{h}',
    '\'': '\'',
    'A': 'A',
    'Aa': r'\={A}',
    'I': 'I',
    'Ee': r'\={\I}',
    'U': 'U',
    'Oo': r'\={U}',
    'RR': r'\d{R}',
    'E': r'\={E}',
    'Ai': 'Ai',
    'O': r'\={O}',
    'Ow': 'Ow',
    'Au': 'Au',
    'MM': r'\d{M}',
    'HH': r'\d{H}',
    '\'': '\'',
# Consonants
# Note that many kinds of half-letters before h are impossible (and are likely never used in any case)
    'k': 'k',
    'kh': 'kh',
    'g': 'g',
    'gh': 'gh',
    'HN': r'\.{n}',
    'c': 'c',
    'ch': 'ch',
    'j': 'j',
    'jh': 'jh',
    'Hn': r'\~{n}',
    'tT': r'\d{t}',
    'tTh': r'\d{t}h',
    'dD': r'\d{d}',
    'dDh': r'\d{d}h',
    'nN': r'\d{n}',
    't': 't',
    'th': 'th',
    'd': 'd',
    'dh': 'dh',
    'n': 'n',
    'p': 'p',
    'ph': 'ph',
    'b': 'b',
    'bh': 'bh',
    'm': 'm',
    'y': 'y',
    'r': 'r',
    'l': 'l',
    'lL': r'\d{l}',
    'v': 'v',
    'sh': '\\\'{s}',
    'sH': r'\.{s}',
    's': 's',
    'h': 'h',
    'K': 'K',
    'Kh': 'Kh',
    'G': 'G',
    'Gh': 'Gh',
    #'HN': r'\.{N}', # No capital version, since no words start with this letter
    'C': 'C',
    'Ch': 'Ch',
    'J': 'J',
    'Jh': 'Jh',
    #'Hn': r'\~{N}', # No capital version, since no words start with this letter
    'TT': r'\d{T}',
    'TTh': r'\d{T}h',
    'DD': r'\d{D}',
    'DDh': r'\d{D}h',
    'NN': r'\d{N}',
    'T': 'T',
    'Th': 'Th',
    'D': 'D',
    'Dh': 'Dh',
    'N': 'N',
    'P': 'P',
    'Ph': 'Ph',
    'B': 'B',
    'Bh': 'Bh',
    'M': 'M',
    'Y': 'Y',
    'R': 'R',
    'L': 'L',
    'LL': r'\d{L}',
    'V': 'V',
    'Sh': '\\\'{S}',
    'SH': r'\.{S}',
    'S': 'S',
    'H': 'H',
}
