default:
  pattern: # None by default. Must be set by the talam
  jathi:   # None by default. Must be set by the talam
  nadai: 4
  kalai: 1

# Alankarams
dhruva:
  pattern: l d l l
  jathi: 4
rupaka_varisai: # The form used in varisais
  pattern: d l
  jathi: 4
triputa:
  pattern: l d d
  jathi: 3
matya:
  pattern: l d l
  jathi: 4
jhampa:
  pattern: l a d
  jathi: 7
ata:
  pattern: l l d d
  jathi: 5
eka:
  pattern: l
  jathi: 4

# Special talas
adi:
  pattern: l d d
  jathi: 4
  newlines:
    - for: [0, 2] # [nadai, kalai]; 0 nadai means for all nadais
      positions: [4, ] # After the fourth beat
rupaka: # The form used in krithis
  pattern: l
  jathi: 3
misra_capu:
  pattern: l
  jathi: 7
  split: # Position of | splitter
    - for: # None means "all"
      positions: [3, 5] # After 3rd and 5th beats
khanda_capu:
  pattern: l
  jathi: 5
  split: # Position of | splitter
    - for: # None means "all"
      positions: [2, ] # After 2nd beat
